name: EconomyAPI
main: com.easterfg.economyapi.EconomyAPI
api: ["1.0.6", "1.0.5"]
version: "1.1.0"
load: STARTUP
author: EasterFG

commands:
  money:
    description: "操作玩家金币类核心命令"
    permission: command.op
  mymoney:
    description: "玩家查看自己的金币"
    permission: command.player
  pay:
    description: "玩家交易金币"
    permission: command.player
  point:
    description: "点券系统操作类核心命令"
    permission: command.op
  mypoint:
    description: "查看自己拥有的点券"
    permission: command.player

permissions:
  command.op:
    default: "op"
  command.player:
    default: "true"